name: img2mol

channels:
  - rdkit
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.2.4
  - notebook=6.4.2
  - pillow=8.0.1
  - numpy=1.19.2
  - rdkit=2020.03.1
  - cudatoolkit=11.0
  - torchvision=0.8.0
  - torchaudio=0.7.0
  - pytorch=1.7.0
  - pytorch-lightning=1.0.8